[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  SECRETS_SCAN_SMART_DETECTION_OMIT_VALUES = "AIzaSyCLZW6tjwb4PbVGqhKJOOszIo9vaHB3z-o"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
